% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames*,x11names*}{xcolor}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Week 3 - Homework},
  pdfauthor={STAT 420, Summer 2021, D. Unger},
  colorlinks=true,
  linkcolor=Maroon,
  filecolor=Maroon,
  citecolor=Blue,
  urlcolor=cyan,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{Week 3 - Homework}
\author{STAT 420, Summer 2021, D. Unger}
\date{}

\begin{document}
\maketitle

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{exercise-1-using-lm-for-inference}{%
\subsection{\texorpdfstring{Exercise 1 (Using \texttt{lm} for
Inference)}{Exercise 1 (Using lm for Inference)}}\label{exercise-1-using-lm-for-inference}}

For this exercise we will use the \texttt{cats} dataset from the
\texttt{MASS} package. You should use \texttt{?cats} to learn about the
background of this dataset.

\textbf{(a)} Fit the following simple linear regression model in
\texttt{R}. Use heart weight as the response and body weight as the
predictor.

\[
Y_i = \beta_0 + \beta_1 x_i + \epsilon_i
\]

Store the results in a variable called \texttt{cat\_model}. Use a \(t\)
test to test the significance of the regression. Report the following:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(MASS)}
\NormalTok{cats }\OtherTok{\textless{}{-}}\NormalTok{ MASS}\SpecialCharTok{::}\NormalTok{cats}
\NormalTok{cat\_model }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(Hwt }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Bwt, }\AttributeTok{data =}\NormalTok{ cats)}
\FunctionTok{summary}\NormalTok{(cat\_model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Hwt ~ Bwt, data = cats)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.5694 -0.9634 -0.0921  1.0426  5.1238 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  -0.3567     0.6923  -0.515    0.607    
## Bwt           4.0341     0.2503  16.119   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.452 on 142 degrees of freedom
## Multiple R-squared:  0.6466, Adjusted R-squared:  0.6441 
## F-statistic: 259.8 on 1 and 142 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{itemize}
\item
  The null and alternative hypotheses Null hypothesis -
  \[H_0: \beta_1 = 0\] Alternative hypothesis - \[H_1: \beta_1 \neq 0\]
\item
  The value of the test statistic
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{beta\_0\_hat\_t }\OtherTok{\textless{}{-}} \FunctionTok{summary}\NormalTok{(cat\_model)}\SpecialCharTok{$}\NormalTok{coefficients[}\StringTok{"(Intercept)"}\NormalTok{,}\StringTok{"t value"}\NormalTok{]}
\NormalTok{beta\_1\_hat\_t }\OtherTok{\textless{}{-}} \FunctionTok{summary}\NormalTok{(cat\_model)}\SpecialCharTok{$}\NormalTok{coefficients[}\StringTok{"Bwt"}\NormalTok{,}\StringTok{"t value"}\NormalTok{]}
\NormalTok{beta\_0\_hat\_t}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -0.5152019
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{beta\_1\_hat\_t}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 16.11939
\end{verbatim}

\begin{itemize}
\tightlist
\item
  The p-value of the test
\end{itemize}

For \[\beta_1\] p value = \textless2e-16

\begin{itemize}
\item
  A statistical decision at \(\alpha = 0.05\) Reject the null
  hypothesis.
\item
  A conclusion in the context of the problem Heart weight has a
  significant linear relationship with body weight.
\end{itemize}

When reporting these, you should explicitly state them in your document,
not assume that a reader will find and interpret them from a large block
of \texttt{R} output.

\textbf{(b)} Calculate a 95\% confidence interval for \(\beta_1\). Give
an interpretation of the interval in the context of the problem.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{confint}\NormalTok{(cat\_model, }\AttributeTok{level =} \FloatTok{0.95}\NormalTok{)[}\StringTok{\textquotesingle{}Bwt\textquotesingle{}}\NormalTok{,]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    2.5 %   97.5 % 
## 3.539343 4.528782
\end{verbatim}

We are 95\% confident that the true change in mean heart weight for an
increase in body weight of 1 kg is between 3.539343 and 4.528782.

\textbf{(c)} Calculate a 90\% confidence interval for \(\beta_0\). Give
an interpretation of the interval in the context of the problem.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{confint}\NormalTok{(cat\_model, }\AttributeTok{level =} \FloatTok{0.95}\NormalTok{)[}\StringTok{\textquotesingle{}(Intercept)\textquotesingle{}}\NormalTok{,]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     2.5 %    97.5 % 
## -1.725163  1.011838
\end{verbatim}

We are 90\% confident that the true change in heart weight when the body
weight is 0 is between -1.725163 1.011838.

\textbf{(d)} Use a 90\% confidence interval to estimate the mean heart
weight for body weights of 2.1 and 2.8 kilograms. Which of the two
intervals is wider? Why?

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{body\_weights }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FloatTok{2.1}\NormalTok{, }\FloatTok{2.8}\NormalTok{)}
\NormalTok{bw\_df }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{Bwt =}\NormalTok{ body\_weights)}
\FunctionTok{predict}\NormalTok{(cat\_model,  }\AttributeTok{newdata =}\NormalTok{ bw\_df, }
        \AttributeTok{interval =} \FunctionTok{c}\NormalTok{(}\StringTok{"confidence"}\NormalTok{), }\AttributeTok{level =} \FloatTok{0.90}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         fit       lwr       upr
## 1  8.114869  7.787882  8.441856
## 2 10.938713 10.735843 11.141583
\end{verbatim}

2.1 kilograms is wider. It's father from \[\bar{x}\].

\textbf{(e)} Use a 90\% prediction interval to predict the heart weight
for body weights of 2.8 and 4.2 kilograms.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{body\_weights }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FloatTok{2.8}\NormalTok{, }\FloatTok{4.2}\NormalTok{)}
\NormalTok{bw\_df }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{Bwt =}\NormalTok{ body\_weights)}
\FunctionTok{predict}\NormalTok{(cat\_model,  }\AttributeTok{newdata =}\NormalTok{ bw\_df, }
        \AttributeTok{interval =} \FunctionTok{c}\NormalTok{(}\StringTok{"prediction"}\NormalTok{), }\AttributeTok{level =} \FloatTok{0.90}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        fit       lwr      upr
## 1 10.93871  8.525541 13.35189
## 2 16.58640 14.097100 19.07570
\end{verbatim}

\textbf{(f)} Create a scatterplot of the data. Add the regression line,
95\% confidence bands, and 95\% prediction bands.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{hwt\_grid }\OtherTok{=} \FunctionTok{seq}\NormalTok{(}\FunctionTok{min}\NormalTok{(cats}\SpecialCharTok{$}\NormalTok{Bwt), }\FunctionTok{max}\NormalTok{(cats}\SpecialCharTok{$}\NormalTok{Bwt), }\AttributeTok{by =} \FloatTok{0.01}\NormalTok{)}
\NormalTok{dist\_ci\_band }\OtherTok{=} \FunctionTok{predict}\NormalTok{(cat\_model, }
                       \AttributeTok{newdata =} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{Bwt =}\NormalTok{ hwt\_grid), }
                       \AttributeTok{interval =} \StringTok{"confidence"}\NormalTok{, }\AttributeTok{level =} \FloatTok{0.99}\NormalTok{)}
\NormalTok{dist\_pi\_band }\OtherTok{=} \FunctionTok{predict}\NormalTok{(cat\_model, }
                       \AttributeTok{newdata =} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{Bwt =}\NormalTok{ hwt\_grid), }
                       \AttributeTok{interval =} \StringTok{"prediction"}\NormalTok{, }\AttributeTok{level =} \FloatTok{0.99}\NormalTok{) }

\FunctionTok{plot}\NormalTok{(Hwt }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Bwt, }\AttributeTok{data =}\NormalTok{ cats,}
     \AttributeTok{xlab =} \StringTok{"Body Weight (In kilograms)"}\NormalTok{,}
     \AttributeTok{ylab =} \StringTok{"Heart Weight(In Kilograms)"}\NormalTok{,}
     \AttributeTok{main =} \StringTok{"Heart Weight vs Body Weight"}\NormalTok{,}
     \AttributeTok{pch  =} \DecValTok{20}\NormalTok{,}
     \AttributeTok{cex  =} \DecValTok{2}\NormalTok{,}
     \AttributeTok{col  =} \StringTok{"grey"}\NormalTok{,}
     \AttributeTok{ylim =} \FunctionTok{c}\NormalTok{(}\FunctionTok{min}\NormalTok{(dist\_pi\_band), }\FunctionTok{max}\NormalTok{(dist\_pi\_band)))}
\FunctionTok{abline}\NormalTok{(cat\_model, }\AttributeTok{lwd =} \DecValTok{5}\NormalTok{, }\AttributeTok{col =} \StringTok{"darkorange"}\NormalTok{)}

\FunctionTok{lines}\NormalTok{(hwt\_grid, dist\_ci\_band[,}\StringTok{"lwr"}\NormalTok{], }\AttributeTok{col =} \StringTok{"dodgerblue"}\NormalTok{, }\AttributeTok{lwd =} \DecValTok{3}\NormalTok{, }\AttributeTok{lty =} \DecValTok{2}\NormalTok{)}
\FunctionTok{lines}\NormalTok{(hwt\_grid, dist\_ci\_band[,}\StringTok{"upr"}\NormalTok{], }\AttributeTok{col =} \StringTok{"dodgerblue"}\NormalTok{, }\AttributeTok{lwd =} \DecValTok{3}\NormalTok{, }\AttributeTok{lty =} \DecValTok{2}\NormalTok{)}
\FunctionTok{lines}\NormalTok{(hwt\_grid, dist\_pi\_band[,}\StringTok{"lwr"}\NormalTok{], }\AttributeTok{col =} \StringTok{"dodgerblue"}\NormalTok{, }\AttributeTok{lwd =} \DecValTok{3}\NormalTok{, }\AttributeTok{lty =} \DecValTok{3}\NormalTok{)}
\FunctionTok{lines}\NormalTok{(hwt\_grid, dist\_pi\_band[,}\StringTok{"upr"}\NormalTok{], }\AttributeTok{col =} \StringTok{"dodgerblue"}\NormalTok{, }\AttributeTok{lwd =} \DecValTok{3}\NormalTok{, }\AttributeTok{lty =} \DecValTok{3}\NormalTok{)}
\FunctionTok{points}\NormalTok{(}\FunctionTok{mean}\NormalTok{(cats}\SpecialCharTok{$}\NormalTok{Hwt), }\FunctionTok{mean}\NormalTok{(cats}\SpecialCharTok{$}\NormalTok{Bwt), }\AttributeTok{pch =} \StringTok{"+"}\NormalTok{, }\AttributeTok{cex =} \DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{w03-hw-assign-su21_files/figure-latex/1f-1.pdf}

\textbf{(g)} Use a \(t\) test to test:

\begin{itemize}
\tightlist
\item
  \(H_0: \beta_1 = 4\)
\item
  \(H_1: \beta_1 \neq 4\)
\end{itemize}

Report the following:

\begin{itemize}
\tightlist
\item
  The value of the test statistic
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{beta\_hat }\OtherTok{\textless{}{-}} \FunctionTok{summary}\NormalTok{(cat\_model)}\SpecialCharTok{$}\NormalTok{coefficients[}\DecValTok{2}\NormalTok{,}\DecValTok{1}\NormalTok{]}
\NormalTok{beta\_1\_se }\OtherTok{\textless{}{-}} \FunctionTok{summary}\NormalTok{(cat\_model)}\SpecialCharTok{$}\NormalTok{coefficients[}\DecValTok{2}\NormalTok{, }\DecValTok{2}\NormalTok{]}
\NormalTok{beta\_1\_0 }\OtherTok{\textless{}{-}} \DecValTok{4}
\NormalTok{beta\_1\_hat\_t }\OtherTok{\textless{}{-}}\NormalTok{ (beta\_hat }\SpecialCharTok{{-}}\NormalTok{ beta\_1\_0) }\SpecialCharTok{/}\NormalTok{ beta\_1\_se}
\NormalTok{beta\_1\_hat\_t}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1361084
\end{verbatim}

\begin{itemize}
\tightlist
\item
  The p-value of the test
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{2} \SpecialCharTok{*} \FunctionTok{pt}\NormalTok{(}\SpecialCharTok{{-}}\FunctionTok{abs}\NormalTok{(beta\_1\_hat\_t), }\AttributeTok{df =} \FunctionTok{nrow}\NormalTok{(cats) }\SpecialCharTok{{-}} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.8919283
\end{verbatim}

\begin{itemize}
\tightlist
\item
  A statistical decision at \(\alpha = 0.05\)
\end{itemize}

Fail to reject the \[H_0\]. When reporting these, you should explicitly
state them in your document, not assume that a reader will find and
interpret them from a large block of \texttt{R} output.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{exercise-2-more-lm-for-inference}{%
\subsection{\texorpdfstring{Exercise 2 (More \texttt{lm} for
Inference)}{Exercise 2 (More lm for Inference)}}\label{exercise-2-more-lm-for-inference}}

For this exercise we will use the \texttt{Ozone} dataset from the
\texttt{mlbench} package. You should use \texttt{?Ozone} to learn about
the background of this dataset. You may need to install the
\texttt{mlbench} package. If you do so, do not include code to install
the package in your \texttt{R} Markdown document.

For simplicity, we will re-perform the data cleaning done in the
previous homework.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(Ozone, }\AttributeTok{package =} \StringTok{"mlbench"}\NormalTok{)}
\NormalTok{Ozone }\OtherTok{=}\NormalTok{ Ozone[, }\FunctionTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{, }\DecValTok{6}\NormalTok{, }\DecValTok{7}\NormalTok{, }\DecValTok{8}\NormalTok{)]}
\FunctionTok{colnames}\NormalTok{(Ozone) }\OtherTok{=} \FunctionTok{c}\NormalTok{(}\StringTok{"ozone"}\NormalTok{, }\StringTok{"wind"}\NormalTok{, }\StringTok{"humidity"}\NormalTok{, }\StringTok{"temp"}\NormalTok{)}
\NormalTok{Ozone }\OtherTok{=}\NormalTok{ Ozone[}\FunctionTok{complete.cases}\NormalTok{(Ozone), ]}
\end{Highlighting}
\end{Shaded}

\textbf{(a)} Fit the following simple linear regression model in
\texttt{R}. Use the ozone measurement as the response and wind speed as
the predictor.

\[
Y_i = \beta_0 + \beta_1 x_i + \epsilon_i
\]

Store the results in a variable called \texttt{ozone\_wind\_model}. Use
a \(t\) test to test the significance of the regression. Report the
following:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ozone\_wind\_model }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(ozone }\SpecialCharTok{\textasciitilde{}}\NormalTok{ wind, }\AttributeTok{data =}\NormalTok{ Ozone)}
\FunctionTok{summary}\NormalTok{(ozone\_wind\_model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = ozone ~ wind, data = Ozone)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -10.730  -6.652  -1.752   4.687  26.359 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  11.8636     1.0856  10.928   <2e-16 ***
## wind         -0.0445     0.2032  -0.219    0.827    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 7.985 on 342 degrees of freedom
## Multiple R-squared:  0.0001402,  Adjusted R-squared:  -0.002783 
## F-statistic: 0.04795 on 1 and 342 DF,  p-value: 0.8268
\end{verbatim}

\begin{itemize}
\item
  The null and alternative hypotheses Null - \(H_0: \beta_1 = 0\)
  Alternative - \(H_1: \beta_1 \neq 0\)
\item
  The value of the test statistic For \[\beta_0\] and \[\beta_1\]
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(ozone\_wind\_model)}\SpecialCharTok{$}\NormalTok{coefficients[}\DecValTok{1}\NormalTok{,}\DecValTok{3}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 10.92785
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(ozone\_wind\_model)}\SpecialCharTok{$}\NormalTok{coefficients[}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -0.2189811
\end{verbatim}

\begin{itemize}
\tightlist
\item
  The p-value of the test
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(ozone\_wind\_model)}\SpecialCharTok{$}\NormalTok{coefficients[}\DecValTok{1}\NormalTok{,}\DecValTok{4}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4.818462e-24
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(ozone\_wind\_model)}\SpecialCharTok{$}\NormalTok{coefficients[}\DecValTok{2}\NormalTok{,}\DecValTok{4}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.8267954
\end{verbatim}

\begin{itemize}
\item
  A statistical decision at \(\alpha = 0.01\) Failed to reject null
  hypotheis.
\item
  A conclusion in the context of the problem No significant linear
  relation between ozone and wind.
\end{itemize}

When reporting these, you should explicitly state them in your document,
not assume that a reader will find and interpret them from a large block
of \texttt{R} output.

\textbf{(b)} Fit the following simple linear regression model in
\texttt{R}. Use the ozone measurement as the response and temperature as
the predictor.

\[
Y_i = \beta_0 + \beta_1 x_i + \epsilon_i
\]

Store the results in a variable called \texttt{ozone\_temp\_model}. Use
a \(t\) test to test the significance of the regression. Report the
following:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ozone\_temp\_model }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(ozone }\SpecialCharTok{\textasciitilde{}}\NormalTok{ temp, }\AttributeTok{data =}\NormalTok{ Ozone)}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\item
  The null and alternative hypotheses Null - \(H_0: \beta_1 = 0\)
  Alternative - \(H_1: \beta_1 \neq 0\)
\item
  The value of the test statistic
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(ozone\_temp\_model)}\SpecialCharTok{$}\NormalTok{coefficients[}\DecValTok{1}\NormalTok{,}\DecValTok{3}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -12.48425
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(ozone\_temp\_model)}\SpecialCharTok{$}\NormalTok{coefficients[}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 22.84896
\end{verbatim}

\begin{itemize}
\tightlist
\item
  The p-value of the test
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(ozone\_temp\_model)}\SpecialCharTok{$}\NormalTok{coefficients[}\DecValTok{1}\NormalTok{,}\DecValTok{4}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 9.947455e-30
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(ozone\_temp\_model)}\SpecialCharTok{$}\NormalTok{coefficients[}\DecValTok{2}\NormalTok{,}\DecValTok{4}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 8.153764e-71
\end{verbatim}

\begin{itemize}
\item
  A statistical decision at \(\alpha = 0.01\) Reject the null
  hypothesis.
\item
  A conclusion in the context of the problem There's significant linear
  relationship between temperature and ozone, with significance level
  0.01.
\end{itemize}

When reporting these, you should explicitly state them in your document,
not assume that a reader will find and interpret them from a large block
of \texttt{R} output.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{exercise-3-simulating-sampling-distributions}{%
\subsection{Exercise 3 (Simulating Sampling
Distributions)}\label{exercise-3-simulating-sampling-distributions}}

For this exercise we will simulate data from the following model:

\[
Y_i = \beta_0 + \beta_1 x_i + \epsilon_i
\]

Where \(\epsilon_i \sim N(0, \sigma^2).\) Also, the parameters are known
to be:

\begin{itemize}
\tightlist
\item
  \(\beta_0 = -5\)
\item
  \(\beta_1 = 3.25\)
\item
  \(\sigma^2 = 16\)
\end{itemize}

We will use samples of size \(n = 50\).

\textbf{(a)} Simulate this model \(2000\) times. Each time use
\texttt{lm()} to fit a simple linear regression model, then store the
value of \(\hat{\beta}_0\) and \(\hat{\beta}_1\). Set a seed using
\textbf{your} birthday before performing the simulation. Note, we are
simulating the \(x\) values once, and then they remain fixed for the
remainder of the exercise.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{birthday }\OtherTok{=} \DecValTok{19880210}
\FunctionTok{set.seed}\NormalTok{(birthday)}
\NormalTok{n }\OtherTok{=} \DecValTok{50}
\NormalTok{x }\OtherTok{=} \FunctionTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{10}\NormalTok{, }\AttributeTok{length =}\NormalTok{ n)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sim\_slr }\OtherTok{=} \ControlFlowTok{function}\NormalTok{(x, }\AttributeTok{beta\_0 =} \DecValTok{10}\NormalTok{, }\AttributeTok{beta\_1 =} \DecValTok{5}\NormalTok{, }\AttributeTok{sigma =} \DecValTok{1}\NormalTok{) \{}
\NormalTok{  n }\OtherTok{=} \FunctionTok{length}\NormalTok{(x)}
\NormalTok{  epsilon }\OtherTok{=} \FunctionTok{rnorm}\NormalTok{(n, }\AttributeTok{mean =} \DecValTok{0}\NormalTok{, }\AttributeTok{sd =}\NormalTok{ sigma)}
\NormalTok{  y }\OtherTok{=}\NormalTok{ beta\_0 }\SpecialCharTok{+}\NormalTok{ beta\_1 }\SpecialCharTok{*}\NormalTok{ x }\SpecialCharTok{+}\NormalTok{ epsilon}
  \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{predictor =}\NormalTok{ x, }\AttributeTok{response =}\NormalTok{ y)}
\NormalTok{\}}
\NormalTok{beta\_0\_hats }\OtherTok{\textless{}{-}} \FunctionTok{rep}\NormalTok{(}\DecValTok{0}\NormalTok{, }\AttributeTok{times=}\DecValTok{2000}\NormalTok{)}
\NormalTok{beta\_1\_hats }\OtherTok{\textless{}{-}} \FunctionTok{rep}\NormalTok{(}\DecValTok{0}\NormalTok{, }\AttributeTok{times=} \DecValTok{2000}\NormalTok{)}

\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\DecValTok{2000}\NormalTok{) \{}
\NormalTok{  sim\_res }\OtherTok{\textless{}{-}} \FunctionTok{sim\_slr}\NormalTok{(}\AttributeTok{x =}\NormalTok{ x, }\AttributeTok{beta\_0 =} \SpecialCharTok{{-}}\DecValTok{5}\NormalTok{, }\AttributeTok{beta\_1 =} \FloatTok{3.25}\NormalTok{, }\AttributeTok{sigma =} \DecValTok{4}\NormalTok{)}
\NormalTok{  linear\_model }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(response }\SpecialCharTok{\textasciitilde{}}\NormalTok{ predictor, }\AttributeTok{data =}\NormalTok{ sim\_res)}
  
\NormalTok{  beta\_0\_hats[i] }\OtherTok{\textless{}{-}} \FunctionTok{summary}\NormalTok{(linear\_model)}\SpecialCharTok{$}\NormalTok{coefficients[}\StringTok{"(Intercept)"}\NormalTok{, }\StringTok{"Estimate"}\NormalTok{]}
\NormalTok{  beta\_1\_hats[i] }\OtherTok{\textless{}{-}} \FunctionTok{summary}\NormalTok{(linear\_model)}\SpecialCharTok{$}\NormalTok{coefficients[}\StringTok{"predictor"}\NormalTok{, }\StringTok{"Estimate"}\NormalTok{]}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\textbf{(b)} Create a table that summarizes the results of the
simulations. The table should have two columns, one for
\(\hat{\beta}_0\) and one for \(\hat{\beta}_1\). The table should have
four rows:

\begin{itemize}
\tightlist
\item
  A row for the true expected value given the known values of \(x\)
\item
  A row for the mean of the simulated values
\item
  A row for the true standard deviation given the known values of \(x\)
\item
  A row for the standard deviation of the simulated values
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sigma }\OtherTok{=} \DecValTok{4}
\NormalTok{Sxx }\OtherTok{=} \FunctionTok{sum}\NormalTok{((x }\SpecialCharTok{{-}} \FunctionTok{mean}\NormalTok{(x)) }\SpecialCharTok{\^{}} \DecValTok{2}\NormalTok{)}
\NormalTok{beta\_0\_mean }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(beta\_0\_hats)}
\NormalTok{beta\_1\_mean }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(beta\_1\_hats)}
\NormalTok{beta\_0\_std }\OtherTok{\textless{}{-}} \FunctionTok{sd}\NormalTok{(beta\_0\_hats)}
\NormalTok{beta\_1\_std }\OtherTok{\textless{}{-}} \FunctionTok{sd}\NormalTok{(beta\_1\_hats)}

\NormalTok{beta\_0\_std\_true }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(sigma }\SpecialCharTok{\^{}} \DecValTok{2} \SpecialCharTok{/}\NormalTok{ Sxx)}
\NormalTok{beta\_1\_std\_true }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(sigma }\SpecialCharTok{\^{}} \DecValTok{2} \SpecialCharTok{*}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{/} \DecValTok{2000} \SpecialCharTok{+} \FunctionTok{mean}\NormalTok{(x) }\SpecialCharTok{\^{}} \DecValTok{2} \SpecialCharTok{/}\NormalTok{ Sxx))}

\NormalTok{beta\_0\_col }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\SpecialCharTok{{-}}\DecValTok{5}\NormalTok{, beta\_0\_mean, beta\_0\_std\_true, beta\_0\_std)}
\NormalTok{beta\_1\_col }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FloatTok{3.25}\NormalTok{, beta\_1\_mean, beta\_1\_std\_true, beta\_1\_std)}
\NormalTok{summary\_df }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(beta\_0\_col, beta\_1\_col)}
\end{Highlighting}
\end{Shaded}

\textbf{(c)} Plot two histograms side-by-side:

\begin{itemize}
\tightlist
\item
  A histogram of your simulated values for \(\hat{\beta}_0\). Add the
  normal curve for the true sampling distribution of \(\hat{\beta}_0\).
\item
  A histogram of your simulated values for \(\hat{\beta}_1\). Add the
  normal curve for the true sampling distribution of \(\hat{\beta}_1\).
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{hist}\NormalTok{(beta\_0\_hats, }\AttributeTok{prob =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{breaks =} \DecValTok{20}\NormalTok{, }
     \AttributeTok{xlab =} \FunctionTok{expression}\NormalTok{(}\FunctionTok{hat}\NormalTok{(beta)[}\DecValTok{0}\NormalTok{]), }\AttributeTok{main =} \StringTok{""}\NormalTok{, }\AttributeTok{border =} \StringTok{"dodgerblue"}\NormalTok{)}
\FunctionTok{curve}\NormalTok{(}\FunctionTok{dnorm}\NormalTok{(x, }\AttributeTok{mean =}\NormalTok{ beta\_0\_mean, }\AttributeTok{sd =}\NormalTok{ beta\_0\_std\_true), }
      \AttributeTok{col =} \StringTok{"darkorange"}\NormalTok{, }\AttributeTok{add =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{lwd =} \DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{w03-hw-assign-su21_files/figure-latex/unnamed-chunk-10-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{hist}\NormalTok{(beta\_1\_hats, }\AttributeTok{prob =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{breaks =} \DecValTok{20}\NormalTok{, }
     \AttributeTok{xlab =} \FunctionTok{expression}\NormalTok{(}\FunctionTok{hat}\NormalTok{(beta)[}\DecValTok{1}\NormalTok{]), }\AttributeTok{main =} \StringTok{""}\NormalTok{, }\AttributeTok{border =} \StringTok{"dodgerblue"}\NormalTok{)}
\FunctionTok{curve}\NormalTok{(}\FunctionTok{dnorm}\NormalTok{(x, }\AttributeTok{mean =}\NormalTok{ beta\_1\_mean, }\AttributeTok{sd =}\NormalTok{ beta\_1\_std\_true), }
      \AttributeTok{col =} \StringTok{"darkorange"}\NormalTok{, }\AttributeTok{add =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{lwd =} \DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{w03-hw-assign-su21_files/figure-latex/unnamed-chunk-10-2.pdf}
***

\hypertarget{exercise-4-simulating-confidence-intervals}{%
\subsection{Exercise 4 (Simulating Confidence
Intervals)}\label{exercise-4-simulating-confidence-intervals}}

For this exercise we will simulate data from the following model:

\[
Y_i = \beta_0 + \beta_1 x_i + \epsilon_i
\]

Where \(\epsilon_i \sim N(0, \sigma^2).\) Also, the parameters are known
to be:

\begin{itemize}
\tightlist
\item
  \(\beta_0 = 5\)
\item
  \(\beta_1 = 2\)
\item
  \(\sigma^2 = 9\)
\end{itemize}

We will use samples of size \(n = 25\).

Our goal here is to use simulation to verify that the confidence
intervals really do have their stated confidence level. Do \textbf{not}
use the \texttt{confint()} function for this entire exercise.

\textbf{(a)} Simulate this model \(2500\) times. Each time use
\texttt{lm()} to fit a simple linear regression model, then store the
value of \(\hat{\beta}_1\) and \(s_e\). Set a seed using \textbf{your}
birthday before performing the simulation. Note, we are simulating the
\(x\) values once, and then they remain fixed for the remainder of the
exercise.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{birthday }\OtherTok{=} \DecValTok{19880210}
\FunctionTok{set.seed}\NormalTok{(birthday)}
\NormalTok{n }\OtherTok{=} \DecValTok{25}
\NormalTok{x }\OtherTok{=} \FunctionTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FloatTok{2.5}\NormalTok{, }\AttributeTok{length =}\NormalTok{ n)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{beta\_1\_hat\_seq }\OtherTok{=} \FunctionTok{rep}\NormalTok{(}\DecValTok{0}\NormalTok{, }\AttributeTok{times=}\DecValTok{2500}\NormalTok{)}
\NormalTok{s\_e\_seq }\OtherTok{=} \FunctionTok{rep}\NormalTok{(}\DecValTok{0}\NormalTok{, }\AttributeTok{times =} \DecValTok{2500}\NormalTok{)}

\ControlFlowTok{for}\NormalTok{(i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\DecValTok{2500}\NormalTok{) \{}
\NormalTok{  sim\_res }\OtherTok{\textless{}{-}} \FunctionTok{sim\_slr}\NormalTok{(}\AttributeTok{x =}\NormalTok{ x, }\AttributeTok{beta\_0 =} \DecValTok{5}\NormalTok{, }\AttributeTok{beta\_1 =} \DecValTok{2}\NormalTok{, }\AttributeTok{sigma =} \DecValTok{3}\NormalTok{)}
\NormalTok{  linear\_model }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(response }\SpecialCharTok{\textasciitilde{}}\NormalTok{ predictor, }\AttributeTok{data =}\NormalTok{ sim\_res)}
  

\NormalTok{  beta\_1\_hat\_seq[i] }\OtherTok{\textless{}{-}} \FunctionTok{summary}\NormalTok{(linear\_model)}\SpecialCharTok{$}\NormalTok{coefficients[}\StringTok{"predictor"}\NormalTok{, }\StringTok{"Estimate"}\NormalTok{]}
\NormalTok{  s\_e\_seq[i] }\OtherTok{\textless{}{-}} \FunctionTok{summary}\NormalTok{(linear\_model)}\SpecialCharTok{$}\NormalTok{coefficients[}\StringTok{"predictor"}\NormalTok{, }\StringTok{"Std. Error"}\NormalTok{]}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\textbf{(b)} For each of the \(\hat{\beta}_1\) that you simulated,
calculate a 95\% confidence interval. Store the lower limits in a vector
\texttt{lower\_95} and the upper limits in a vector \texttt{upper\_95}.
Some hints:

\begin{itemize}
\tightlist
\item
  You will need to use \texttt{qt()} to calculate the critical value,
  which will be the same for each interval.
\item
  Remember that \texttt{x} is fixed, so \(S_{xx}\) will be the same for
  each interval.
\item
  You could, but do not need to write a \texttt{for} loop. Remember
  vectorized operations.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{crit }\OtherTok{=} \FunctionTok{qt}\NormalTok{(}\FloatTok{0.95}\NormalTok{, }\AttributeTok{df =} \DecValTok{25} \SpecialCharTok{{-}} \DecValTok{2}\NormalTok{)}
\NormalTok{lower\_95 }\OtherTok{\textless{}{-}}\NormalTok{ beta\_1\_hat\_seq }\SpecialCharTok{{-}}\NormalTok{ crit }\SpecialCharTok{*}\NormalTok{ s\_e\_seq}
\NormalTok{upper\_95 }\OtherTok{\textless{}{-}}\NormalTok{ beta\_1\_hat\_seq }\SpecialCharTok{+}\NormalTok{ crit }\SpecialCharTok{*}\NormalTok{ s\_e\_seq}
\end{Highlighting}
\end{Shaded}

\textbf{(c)} What proportion of these intervals contains the true value
of \(\beta_1\)?

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{beta\_1 }\OtherTok{\textless{}{-}} \DecValTok{2}
\NormalTok{interval\_df }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(lower\_95, upper\_95)}
\NormalTok{interval\_df }\OtherTok{\textless{}{-}}\NormalTok{ interval\_df[interval\_df}\SpecialCharTok{$}\NormalTok{lower\_95 }\SpecialCharTok{\textless{}=} \DecValTok{2}\NormalTok{,]}
\NormalTok{interval\_df }\OtherTok{\textless{}{-}}\NormalTok{ interval\_df[interval\_df}\SpecialCharTok{$}\NormalTok{upper\_95 }\SpecialCharTok{\textgreater{}=} \DecValTok{2}\NormalTok{,]}
\FunctionTok{nrow}\NormalTok{(interval\_df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2261
\end{verbatim}

\textbf{(d)} Based on these intervals, what proportion of the
simulations would reject the test \(H_0: \beta_1 = 0\) vs
\(H_1: \beta_1 \neq 0\) at \(\alpha = 0.05\)?

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{2243}\SpecialCharTok{/}\DecValTok{2500}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.8972
\end{verbatim}

\textbf{(e)} For each of the \(\hat{\beta}_1\) that you simulated,
calculate a 99\% confidence interval. Store the lower limits in a vector
\texttt{lower\_99} and the upper limits in a vector \texttt{upper\_99}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{crit }\OtherTok{=} \FunctionTok{qt}\NormalTok{(}\FloatTok{0.99}\NormalTok{, }\AttributeTok{df =} \DecValTok{25} \SpecialCharTok{{-}} \DecValTok{2}\NormalTok{)}
\NormalTok{lower\_99 }\OtherTok{\textless{}{-}}\NormalTok{ beta\_1\_hat\_seq }\SpecialCharTok{{-}}\NormalTok{ crit }\SpecialCharTok{*}\NormalTok{ s\_e\_seq}
\NormalTok{upper\_99 }\OtherTok{\textless{}{-}}\NormalTok{ beta\_1\_hat\_seq }\SpecialCharTok{+}\NormalTok{ crit }\SpecialCharTok{*}\NormalTok{ s\_e\_seq}
\NormalTok{interval\_df }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(lower\_99, upper\_99)}
\NormalTok{interval\_df }\OtherTok{\textless{}{-}}\NormalTok{ interval\_df[interval\_df}\SpecialCharTok{$}\NormalTok{lower\_99 }\SpecialCharTok{\textless{}=} \DecValTok{2}\NormalTok{,]}
\NormalTok{interval\_df }\OtherTok{\textless{}{-}}\NormalTok{ interval\_df[interval\_df}\SpecialCharTok{$}\NormalTok{upper\_99 }\SpecialCharTok{\textgreater{}=} \DecValTok{2}\NormalTok{,]}
\end{Highlighting}
\end{Shaded}

\textbf{(f)} What proportion of these intervals contains the true value
of \(\beta_1\)?

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{nrow}\NormalTok{(interval\_df)}\SpecialCharTok{/}\DecValTok{2500}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.9824
\end{verbatim}

\textbf{(g)} Based on these intervals, what proportion of the
simulations would reject the test \(H_0: \beta_1 = 0\) vs
\(H_1: \beta_1 \neq 0\) at \(\alpha = 0.01\)?

0.9792

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{exercise-5-prediction-intervals-without-predict}{%
\subsection{\texorpdfstring{Exercise 5 (Prediction Intervals ``without''
\texttt{predict})}{Exercise 5 (Prediction Intervals ``without'' predict)}}\label{exercise-5-prediction-intervals-without-predict}}

Write a function named \texttt{calc\_pred\_int} that performs calculates
prediction intervals:

\[
\hat{y}(x) \pm t_{\alpha/2, n - 2} \cdot s_e\sqrt{1 + \frac{1}{n}+\frac{(x-\bar{x})^2}{S_{xx}}}.
\]

for the linear model

\[
Y_i = \beta_0 + \beta_1 x_i + \epsilon_i.
\]

\textbf{(a)} Write this function. You may use the \texttt{predict()}
function, but you may \textbf{not} supply a value for the \texttt{level}
argument of \texttt{predict()}. (You can certainly use
\texttt{predict()} any way you would like in order to check your work.)

The function should take three inputs:

\begin{itemize}
\tightlist
\item
  \texttt{model}, a model object that is the result of fitting the SLR
  model with \texttt{lm()}
\item
  \texttt{newdata}, a data frame with a single observation (row)

  \begin{itemize}
  \tightlist
  \item
    This data frame will need to have a variable (column) with the same
    name as the data used to fit \texttt{model}.
  \end{itemize}
\item
  \texttt{level}, the level (0.90, 0.95, etc) for the interval with a
  default value of \texttt{0.95}
\end{itemize}

The function should return a named vector with three elements:

\begin{itemize}
\tightlist
\item
  \texttt{estimate}, the midpoint of the interval
\item
  \texttt{lower}, the lower bound of the interval
\item
  \texttt{upper}, the upper bound of the interval
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{calc\_pred\_int }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{ (model, newdata, }\AttributeTok{level =} \FloatTok{0.95}\NormalTok{) \{}

  
\NormalTok{  beta\_hat\_1 }\OtherTok{=} \FunctionTok{coef}\NormalTok{(model)[[}\DecValTok{2}\NormalTok{]];}
\NormalTok{  beta\_hat\_0 }\OtherTok{=} \FunctionTok{coef}\NormalTok{(model)[[}\DecValTok{1}\NormalTok{]];}
\NormalTok{  y\_hat }\OtherTok{=}\NormalTok{ beta\_hat\_0 }\SpecialCharTok{+}\NormalTok{ beta\_hat\_1 }\SpecialCharTok{*}\NormalTok{ x;}
\NormalTok{  e }\OtherTok{=} \FunctionTok{resid}\NormalTok{(model);}
\NormalTok{  n }\OtherTok{=} \FunctionTok{length}\NormalTok{(}\FunctionTok{resid}\NormalTok{(model));}
\NormalTok{  x }\OtherTok{=} \FunctionTok{as.vector}\NormalTok{(model}\SpecialCharTok{$}\NormalTok{model[,}\DecValTok{2}\NormalTok{]);}
\NormalTok{  y }\OtherTok{=} \FunctionTok{as.vector}\NormalTok{(model}\SpecialCharTok{$}\NormalTok{model[,}\DecValTok{1}\NormalTok{]);}
\NormalTok{  x\_bar }\OtherTok{=} \FunctionTok{mean}\NormalTok{(x);}
  
\NormalTok{  estimate }\OtherTok{=}\NormalTok{ beta\_hat\_0 }\SpecialCharTok{+}\NormalTok{ beta\_hat\_1 }\SpecialCharTok{*}\NormalTok{ newdata[[}\DecValTok{1}\NormalTok{]];}
\NormalTok{  se }\OtherTok{=} \FunctionTok{summary}\NormalTok{(model)}\SpecialCharTok{$}\NormalTok{coefficients[}\DecValTok{2}\NormalTok{, }\StringTok{"Std. Error"}\NormalTok{]}
\NormalTok{  Sxx }\OtherTok{=} \FunctionTok{sum}\NormalTok{((x }\SpecialCharTok{{-}} \FunctionTok{mean}\NormalTok{(x)) }\SpecialCharTok{\^{}} \DecValTok{2}\NormalTok{)}
  
\NormalTok{  pred }\OtherTok{=}\NormalTok{ se }\SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(}\DecValTok{1} \SpecialCharTok{+}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{/}\FunctionTok{length}\NormalTok{(x)) }\SpecialCharTok{+}\NormalTok{ ((newdata[[}\DecValTok{1}\NormalTok{]] }\SpecialCharTok{{-}}\NormalTok{ x\_bar)}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{/}\NormalTok{ Sxx));}
  \FunctionTok{c}\NormalTok{(}\StringTok{"estimate"} \OtherTok{=}\NormalTok{ estimate, }\StringTok{"lower"} \OtherTok{=}\NormalTok{ estimate }\SpecialCharTok{{-}}\NormalTok{ pred, }\StringTok{"upper"} \OtherTok{=}\NormalTok{ estimate }\SpecialCharTok{+}\NormalTok{ pred);}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\textbf{(b)} After writing the function, run this code:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{newcat\_1 }\OtherTok{=} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{Bwt =} \FloatTok{4.0}\NormalTok{)}
\FunctionTok{calc\_pred\_int}\NormalTok{(cat\_model, newcat\_1)}
\end{Highlighting}
\end{Shaded}

\textbf{(c)} After writing the function, run this code:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{newcat\_2 }\OtherTok{=} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{Bwt =} \FloatTok{3.3}\NormalTok{)}
\FunctionTok{calc\_pred\_int}\NormalTok{(cat\_model, newcat\_2, }\AttributeTok{level =} \FloatTok{0.90}\NormalTok{)}
\end{Highlighting}
\end{Shaded}


\end{document}
