% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames*,x11names*}{xcolor}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Week 9 - Homework},
  pdfauthor={STAT 420, Summer 2021, D. Unger},
  colorlinks=true,
  linkcolor=Maroon,
  filecolor=Maroon,
  citecolor=Blue,
  urlcolor=cyan,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{Week 9 - Homework}
\author{STAT 420, Summer 2021, D. Unger}
\date{}

\begin{document}
\maketitle

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{exercise-1-longley-macroeconomic-data}{%
\subsection{\texorpdfstring{Exercise 1 (\texttt{longley} Macroeconomic
Data)}{Exercise 1 (longley Macroeconomic Data)}}\label{exercise-1-longley-macroeconomic-data}}

The built-in dataset \texttt{longley} contains macroeconomic data for
predicting employment. We will attempt to model the \texttt{Employed}
variable.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{View}\NormalTok{(longley)}
\NormalTok{?longley}
\end{Highlighting}
\end{Shaded}

\textbf{(a)} What is the largest correlation between any pair of
predictors in the dataset?

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{round}\NormalTok{(}\FunctionTok{cor}\NormalTok{(longley), }\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##              GNP.deflator  GNP Unemployed Armed.Forces Population Year Employed
## GNP.deflator         1.00 0.99       0.62         0.46       0.98 0.99     0.97
## GNP                  0.99 1.00       0.60         0.45       0.99 1.00     0.98
## Unemployed           0.62 0.60       1.00        -0.18       0.69 0.67     0.50
## Armed.Forces         0.46 0.45      -0.18         1.00       0.36 0.42     0.46
## Population           0.98 0.99       0.69         0.36       1.00 0.99     0.96
## Year                 0.99 1.00       0.67         0.42       0.99 1.00     0.97
## Employed             0.97 0.98       0.50         0.46       0.96 0.97     1.00
\end{verbatim}

The largest correlation equals to 1 after rounding. GNP and Year.

\textbf{(b)} Fit a model with \texttt{Employed} as the response and the
remaining variables as predictors. Calculate and report the variance
inflation factor (VIF) for each of the predictors. Which variable has
the largest VIF? Do any of the VIFs suggest multicollinearity?

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(faraway)}
\NormalTok{longley\_mod }\OtherTok{=} \FunctionTok{lm}\NormalTok{(Employed }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{data =}\NormalTok{ longley)}
\FunctionTok{vif}\NormalTok{(longley\_mod)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## GNP.deflator          GNP   Unemployed Armed.Forces   Population         Year 
##      135.532     1788.513       33.619        3.589      399.151      758.981
\end{verbatim}

GNP has the largetst VIF, 1788.513. If we use VIF threshould 5, then all
VIFs except Armed.Forces suggest multicollinearity.

\textbf{(c)} What proportion of the observed variation in
\texttt{Population} is explained by a linear relationship with the other
predictors?

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{longley\_mod\_1c }\OtherTok{=} \FunctionTok{lm}\NormalTok{(Population }\SpecialCharTok{\textasciitilde{}}\NormalTok{ . }\SpecialCharTok{{-}}\NormalTok{ Employed, }\AttributeTok{data =}\NormalTok{ longley)}
\FunctionTok{summary}\NormalTok{(longley\_mod\_1c)}\SpecialCharTok{$}\NormalTok{r.squared}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.9975
\end{verbatim}

0.9975

\textbf{(d)} Calculate the partial correlation coefficient for
\texttt{Population} and \texttt{Employed} \textbf{with the effects of
the other predictors removed}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{longley\_mod\_1d\_emp }\OtherTok{=} \FunctionTok{lm}\NormalTok{(Employed }\SpecialCharTok{\textasciitilde{}}\NormalTok{ . }\SpecialCharTok{{-}}\NormalTok{ Population, }\AttributeTok{data =}\NormalTok{ longley)}
\NormalTok{longley\_mod\_1d\_pop }\OtherTok{=} \FunctionTok{lm}\NormalTok{(Population }\SpecialCharTok{\textasciitilde{}}\NormalTok{ . }\SpecialCharTok{{-}}\NormalTok{ Employed, }\AttributeTok{data =}\NormalTok{ longley)}
\FunctionTok{cor}\NormalTok{(}\FunctionTok{resid}\NormalTok{(longley\_mod\_1d\_emp), }\FunctionTok{resid}\NormalTok{(longley\_mod\_1d\_pop))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -0.07514
\end{verbatim}

\textbf{(e)} Fit a new model with \texttt{Employed} as the response and
the predictors from the model in \textbf{(b)} that were significant.
(Use \(\alpha = 0.05\).) Calculate and report the variance inflation
factor for each of the predictors. Which variable has the largest VIF?
Do any of the VIFs suggest multicollinearity?

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{longley\_mod\_1e }\OtherTok{=} \FunctionTok{lm}\NormalTok{(Employed }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Unemployed  }\SpecialCharTok{+}\NormalTok{ Armed.Forces }\SpecialCharTok{+}\NormalTok{ Year, }\AttributeTok{data =}\NormalTok{ longley)}
\FunctionTok{vif}\NormalTok{(longley\_mod\_1e)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Unemployed Armed.Forces         Year 
##        3.318        2.223        3.891
\end{verbatim}

Year has the largest VIF, 3.891. None of the VIFs suggest
multicollinearity.

\textbf{(f)} Use an \(F\)-test to compare the models in parts
\textbf{(b)} and \textbf{(e)}. Report the following:

\begin{itemize}
\tightlist
\item
  The null hypothesis
\item
  The test statistic
\item
  The distribution of the test statistic under the null hypothesis
\item
  The p-value
\item
  A decision
\item
  Which model you prefer, \textbf{(b)} or \textbf{(e)}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{anova}\NormalTok{(longley\_mod\_1e, longley\_mod)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Variance Table
## 
## Model 1: Employed ~ Unemployed + Armed.Forces + Year
## Model 2: Employed ~ GNP.deflator + GNP + Unemployed + Armed.Forces + Population + 
##     Year
##   Res.Df   RSS Df Sum of Sq    F Pr(>F)
## 1     12 1.323                         
## 2      9 0.836  3     0.487 1.75   0.23
\end{verbatim}

Null hypothesis: The parameters for predictor GNP.deflator, GNP,
Population are 0.\\
Test statistic: 1.75\\
Distribution under null hypothesis: F distribution\\
p-value: 0.23 Decision: Failed to reject the null hypothesis. Prefer e
since it has no significant difference with b and is smaller.

\textbf{(g)} Check the assumptions of the model chosen in part
\textbf{(f)}. Do any assumptions appear to be violated?

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(lmtest)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: zoo
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'zoo'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:base':
## 
##     as.Date, as.Date.numeric
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{shapiro.test}\NormalTok{(}\FunctionTok{resid}\NormalTok{(longley\_mod\_1e))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  resid(longley_mod_1e)
## W = 0.93, p-value = 0.2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{bptest}\NormalTok{(longley\_mod\_1e)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  studentized Breusch-Pagan test
## 
## data:  longley_mod_1e
## BP = 2.5, df = 3, p-value = 0.5
\end{verbatim}

Both tests have a p-value larger than 0.05. Failed to reject the null
hypothesises. Does not violate the assumptions.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{exercise-2-credit-data}{%
\subsection{\texorpdfstring{Exercise 2 (\texttt{Credit}
Data)}{Exercise 2 (Credit Data)}}\label{exercise-2-credit-data}}

For this exercise, use the \texttt{Credit} data from the \texttt{ISLR}
package. Use the following code to remove the \texttt{ID} variable which
is not useful for modeling.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ISLR)}
\FunctionTok{data}\NormalTok{(Credit)}
\NormalTok{Credit }\OtherTok{=} \FunctionTok{subset}\NormalTok{(Credit, }\AttributeTok{select =} \SpecialCharTok{{-}}\FunctionTok{c}\NormalTok{(ID))}
\end{Highlighting}
\end{Shaded}

Use \texttt{?Credit} to learn about this dataset.

\textbf{(a)} Find a ``good'' model for \texttt{balance} using the
available predictors. Use any methods seen in class except
transformations of the response. The model should:

\begin{itemize}
\tightlist
\item
  Reach a LOOCV-RMSE below \texttt{140}
\item
  Obtain an adjusted \(R^2\) above \texttt{0.90}
\item
  Fail to reject the Breusch-Pagan test with an \(\alpha\) of \(0.01\)
\item
  Use fewer than 10 \(\beta\) parameters
\end{itemize}

Store your model in a variable called \texttt{mod\_a}. Run the two given
chunks to verify your model meets the requested criteria. If you cannot
find a model that meets all criteria, partial credit will be given for
meeting at least some of the criteria.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{credit\_mod\_2a\_start }\OtherTok{=} \FunctionTok{lm}\NormalTok{(Balance }\SpecialCharTok{\textasciitilde{}} \DecValTok{1}\NormalTok{, }\AttributeTok{data =}\NormalTok{ Credit)}
\NormalTok{credit\_mod\_2a }\OtherTok{=} \FunctionTok{lm}\NormalTok{(Balance }\SpecialCharTok{\textasciitilde{}} \FunctionTok{log}\NormalTok{(Income) }\SpecialCharTok{+}\NormalTok{ Limit }\SpecialCharTok{+}\NormalTok{ Cards }\SpecialCharTok{+}\NormalTok{ Age }\SpecialCharTok{+}\NormalTok{ Education }\SpecialCharTok{+}\NormalTok{ Gender}
                   \SpecialCharTok{+}\NormalTok{ Student }\SpecialCharTok{+}\NormalTok{ Married }\SpecialCharTok{+}\NormalTok{ Ethnicity, }\AttributeTok{data =}\NormalTok{ Credit)}

\CommentTok{\#credit\_mod\_2a\_back\_aic = step(credit\_mod\_2a, direction = "backward")}



\NormalTok{calc\_loocv\_rmse }\OtherTok{=} \ControlFlowTok{function}\NormalTok{(model) \{}
  \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{mean}\NormalTok{((}\FunctionTok{resid}\NormalTok{(model) }\SpecialCharTok{/}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{{-}} \FunctionTok{hatvalues}\NormalTok{(model))) }\SpecialCharTok{\^{}} \DecValTok{2}\NormalTok{))}
\NormalTok{\}}


\NormalTok{mod\_a }\OtherTok{=} \FunctionTok{lm}\NormalTok{(}\AttributeTok{formula =}\NormalTok{ Balance }\SpecialCharTok{\textasciitilde{}} \FunctionTok{log}\NormalTok{(Income) }\SpecialCharTok{+}\NormalTok{ Limit }\SpecialCharTok{+}\NormalTok{ Cards }\SpecialCharTok{+}\NormalTok{ Age }\SpecialCharTok{+}\NormalTok{ Education }\SpecialCharTok{+} 
\NormalTok{    Gender }\SpecialCharTok{+}\NormalTok{ Student }\SpecialCharTok{+}\NormalTok{ Married }\SpecialCharTok{+}\NormalTok{ Ethnicity, }\AttributeTok{data =}\NormalTok{ Credit)}

\FunctionTok{summary}\NormalTok{(mod\_a)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Balance ~ log(Income) + Limit + Cards + Age + Education + 
##     Gender + Student + Married + Ethnicity, data = Credit)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -444.7  -93.2    5.0   98.4  283.5 
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(>|t|)    
## (Intercept)         454.17524   55.56623    8.17  4.3e-15 ***
## log(Income)        -304.62391   13.89381  -21.93  < 2e-16 ***
## Limit                 0.23915    0.00412   58.09  < 2e-16 ***
## Cards                20.26535    4.76489    4.25  2.6e-05 ***
## Age                  -1.00710    0.38451   -2.62   0.0092 ** 
## Education            -2.14021    2.09227   -1.02   0.3070    
## GenderFemale         -1.22208   13.00252   -0.09   0.9252    
## StudentYes          418.74429   21.83890   19.17  < 2e-16 ***
## MarriedYes          -17.22292   13.50933   -1.27   0.2031    
## EthnicityAsian       11.25830   18.49131    0.61   0.5430    
## EthnicityCaucasian   20.30982   16.01986    1.27   0.2056    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 130 on 389 degrees of freedom
## Multiple R-squared:  0.922,  Adjusted R-squared:  0.92 
## F-statistic:  463 on 10 and 389 DF,  p-value: <2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{bptest}\NormalTok{(mod\_a)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  studentized Breusch-Pagan test
## 
## data:  mod_a
## BP = 22, df = 10, p-value = 0.02
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{calc\_loocv\_rmse}\NormalTok{(mod\_a)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 131.8
\end{verbatim}

The model that meets requirement is using log(Income) + Limit + Cards +
Age + Education + Gender + Student + Married + Ethnicity as predictors.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(lmtest)}

\NormalTok{get\_bp\_decision }\OtherTok{=} \ControlFlowTok{function}\NormalTok{(model, alpha) \{}
\NormalTok{  decide }\OtherTok{=} \FunctionTok{unname}\NormalTok{(}\FunctionTok{bptest}\NormalTok{(model)}\SpecialCharTok{$}\NormalTok{p.value }\SpecialCharTok{\textless{}}\NormalTok{ alpha)}
  \FunctionTok{ifelse}\NormalTok{(decide, }\StringTok{"Reject"}\NormalTok{, }\StringTok{"Fail to Reject"}\NormalTok{)}
\NormalTok{\}}

\NormalTok{get\_sw\_decision }\OtherTok{=} \ControlFlowTok{function}\NormalTok{(model, alpha) \{}
\NormalTok{  decide }\OtherTok{=} \FunctionTok{unname}\NormalTok{(}\FunctionTok{shapiro.test}\NormalTok{(}\FunctionTok{resid}\NormalTok{(model))}\SpecialCharTok{$}\NormalTok{p.value }\SpecialCharTok{\textless{}}\NormalTok{ alpha)}
  \FunctionTok{ifelse}\NormalTok{(decide, }\StringTok{"Reject"}\NormalTok{, }\StringTok{"Fail to Reject"}\NormalTok{)}
\NormalTok{\}}

\NormalTok{get\_num\_params }\OtherTok{=} \ControlFlowTok{function}\NormalTok{(model) \{}
  \FunctionTok{length}\NormalTok{(}\FunctionTok{coef}\NormalTok{(model))}
\NormalTok{\}}

\NormalTok{get\_loocv\_rmse }\OtherTok{=} \ControlFlowTok{function}\NormalTok{(model) \{}
  \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{mean}\NormalTok{((}\FunctionTok{resid}\NormalTok{(model) }\SpecialCharTok{/}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{{-}} \FunctionTok{hatvalues}\NormalTok{(model))) }\SpecialCharTok{\^{}} \DecValTok{2}\NormalTok{))}
\NormalTok{\}}

\NormalTok{get\_adj\_r2 }\OtherTok{=} \ControlFlowTok{function}\NormalTok{(model) \{}
  \FunctionTok{summary}\NormalTok{(model)}\SpecialCharTok{$}\NormalTok{adj.r.squared}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{get\_loocv\_rmse}\NormalTok{(mod\_a)}
\FunctionTok{get\_adj\_r2}\NormalTok{(mod\_a)}
\FunctionTok{get\_bp\_decision}\NormalTok{(mod\_a, }\AttributeTok{alpha =} \FloatTok{0.01}\NormalTok{)}
\FunctionTok{get\_num\_params}\NormalTok{(mod\_a)}
\end{Highlighting}
\end{Shaded}

\textbf{(b)} Find another ``good'' model for \texttt{balance} using the
available predictors. Use any methods seen in class except
transformations of the response. The model should:

\begin{itemize}
\tightlist
\item
  Reach a LOOCV-RMSE below \texttt{130}
\item
  Obtain an adjusted \(R^2\) above \texttt{0.85}
\item
  Fail to reject the Shapiro-Wilk test with an \(\alpha\) of \(0.01\)
\item
  Use fewer than 25 \(\beta\) parameters
\end{itemize}

Store your model in a variable called \texttt{mod\_b}. Run the two given
chunks to verify your model meets the requested criteria. If you cannot
find a model that meets all criteria, partial credit will be given for
meeting at least some of the criteria.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mod\_b }\OtherTok{=} \FunctionTok{lm}\NormalTok{(Balance }\SpecialCharTok{\textasciitilde{}}\NormalTok{ (}\FunctionTok{log}\NormalTok{(Income) }\SpecialCharTok{+}\NormalTok{ Limit }\SpecialCharTok{+}\NormalTok{ Cards }\SpecialCharTok{+}\NormalTok{ Age }\SpecialCharTok{+}\NormalTok{ Education }\SpecialCharTok{+}\NormalTok{ Gender}
                   \SpecialCharTok{+}\NormalTok{ Student }\SpecialCharTok{+}\NormalTok{ Married }\SpecialCharTok{+}\NormalTok{ Ethnicity) }\SpecialCharTok{\^{}} \DecValTok{2}\NormalTok{, }\AttributeTok{data =}\NormalTok{ Credit)}

\CommentTok{\#mod\_b = step(mod\_b, direction = "both", scope = Balance \textasciitilde{} (log(Income) + Limit + Cards + Age + Education + Gender}
\CommentTok{\#                   + Student + Married + Ethnicity) \^{} 2)}

\NormalTok{mod\_b }\OtherTok{=} \FunctionTok{lm}\NormalTok{(}\AttributeTok{formula =}\NormalTok{ Balance }\SpecialCharTok{\textasciitilde{}} \FunctionTok{log}\NormalTok{(Income) }\SpecialCharTok{+}\NormalTok{ Limit }\SpecialCharTok{+}\NormalTok{ Cards }\SpecialCharTok{+}\NormalTok{ Age }\SpecialCharTok{+}\NormalTok{ Education }\SpecialCharTok{+} 
\NormalTok{    Gender }\SpecialCharTok{+}\NormalTok{ Student }\SpecialCharTok{+}\NormalTok{ Married }\SpecialCharTok{+}\NormalTok{ Ethnicity }\SpecialCharTok{+} \FunctionTok{log}\NormalTok{(Income)}\SpecialCharTok{:}\NormalTok{Limit }\SpecialCharTok{+} 
    \FunctionTok{log}\NormalTok{(Income)}\SpecialCharTok{:}\NormalTok{Age }\SpecialCharTok{+} \FunctionTok{log}\NormalTok{(Income)}\SpecialCharTok{:}\NormalTok{Education }\SpecialCharTok{+} \FunctionTok{log}\NormalTok{(Income)}\SpecialCharTok{:}\NormalTok{Student }\SpecialCharTok{+} 
\NormalTok{    Limit}\SpecialCharTok{:}\NormalTok{Cards }\SpecialCharTok{+}\NormalTok{ Limit}\SpecialCharTok{:}\NormalTok{Student }\SpecialCharTok{+}\NormalTok{ Cards}\SpecialCharTok{:}\NormalTok{Gender }\SpecialCharTok{+}\NormalTok{ Age}\SpecialCharTok{:}\NormalTok{Education }\SpecialCharTok{+} 
\NormalTok{    Age}\SpecialCharTok{:}\NormalTok{Student }\SpecialCharTok{+}\NormalTok{ Age}\SpecialCharTok{:}\NormalTok{Married }\SpecialCharTok{+}\NormalTok{ Education}\SpecialCharTok{:}\NormalTok{Student }\SpecialCharTok{+}\NormalTok{ Married}\SpecialCharTok{:}\NormalTok{Ethnicity, }
    \AttributeTok{data =}\NormalTok{ Credit)}

\FunctionTok{summary}\NormalTok{(mod\_b)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Balance ~ log(Income) + Limit + Cards + Age + Education + 
##     Gender + Student + Married + Ethnicity + log(Income):Limit + 
##     log(Income):Age + log(Income):Education + log(Income):Student + 
##     Limit:Cards + Limit:Student + Cards:Gender + Age:Education + 
##     Age:Student + Age:Married + Education:Student + Married:Ethnicity, 
##     data = Credit)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -387.4  -85.2   -5.2   78.5  288.0 
## 
## Coefficients:
##                                 Estimate Std. Error t value Pr(>|t|)    
## (Intercept)                   -102.95703  182.91554   -0.56   0.5739    
## log(Income)                   -196.49627   47.35060   -4.15  4.1e-05 ***
## Limit                            0.32356    0.01498   21.61  < 2e-16 ***
## Cards                           -2.22232   10.59890   -0.21   0.8340    
## Age                              7.73498    2.35166    3.29   0.0011 ** 
## Education                      -15.34786   10.47120   -1.47   0.1436    
## GenderFemale                   -48.50602   28.31234   -1.71   0.0875 .  
## StudentYes                     541.06906  148.21379    3.65   0.0003 ***
## MarriedYes                      97.33856   47.35418    2.06   0.0405 *  
## EthnicityAsian                   3.51684   26.79597    0.13   0.8957    
## EthnicityCaucasian              42.20710   21.73631    1.94   0.0529 .  
## log(Income):Limit               -0.02384    0.00337   -7.08  7.3e-12 ***
## log(Income):Age                 -1.27185    0.48904   -2.60   0.0097 ** 
## log(Income):Education            6.47640    2.68617    2.41   0.0164 *  
## log(Income):StudentYes        -101.56776   41.95338   -2.42   0.0160 *  
## Limit:Cards                      0.00278    0.00183    1.52   0.1306    
## Limit:StudentYes                 0.05286    0.01345    3.93   0.0001 ***
## Cards:GenderFemale              14.50437    8.71135    1.66   0.0967 .  
## Age:Education                   -0.19752    0.11168   -1.77   0.0778 .  
## Age:StudentYes                  -3.58696    1.30670   -2.75   0.0063 ** 
## Age:MarriedYes                  -1.51578    0.70552   -2.15   0.0323 *  
## Education:StudentYes            13.37075    7.00024    1.91   0.0569 .  
## MarriedYes:EthnicityAsian        9.10176   34.40781    0.26   0.7915    
## MarriedYes:EthnicityCaucasian  -45.13946   29.11532   -1.55   0.1219    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 114 on 376 degrees of freedom
## Multiple R-squared:  0.942,  Adjusted R-squared:  0.938 
## F-statistic:  263 on 23 and 376 DF,  p-value: <2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{shapiro.test}\NormalTok{(}\FunctionTok{resid}\NormalTok{(mod\_b))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  resid(mod_b)
## W = 0.99, p-value = 0.03
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{calc\_loocv\_rmse}\NormalTok{(mod\_b)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 119
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(lmtest)}

\NormalTok{get\_bp\_decision }\OtherTok{=} \ControlFlowTok{function}\NormalTok{(model, alpha) \{}
\NormalTok{  decide }\OtherTok{=} \FunctionTok{unname}\NormalTok{(}\FunctionTok{bptest}\NormalTok{(model)}\SpecialCharTok{$}\NormalTok{p.value }\SpecialCharTok{\textless{}}\NormalTok{ alpha)}
  \FunctionTok{ifelse}\NormalTok{(decide, }\StringTok{"Reject"}\NormalTok{, }\StringTok{"Fail to Reject"}\NormalTok{)}
\NormalTok{\}}

\NormalTok{get\_sw\_decision }\OtherTok{=} \ControlFlowTok{function}\NormalTok{(model, alpha) \{}
\NormalTok{  decide }\OtherTok{=} \FunctionTok{unname}\NormalTok{(}\FunctionTok{shapiro.test}\NormalTok{(}\FunctionTok{resid}\NormalTok{(model))}\SpecialCharTok{$}\NormalTok{p.value }\SpecialCharTok{\textless{}}\NormalTok{ alpha)}
  \FunctionTok{ifelse}\NormalTok{(decide, }\StringTok{"Reject"}\NormalTok{, }\StringTok{"Fail to Reject"}\NormalTok{)}
\NormalTok{\}}

\NormalTok{get\_num\_params }\OtherTok{=} \ControlFlowTok{function}\NormalTok{(model) \{}
  \FunctionTok{length}\NormalTok{(}\FunctionTok{coef}\NormalTok{(model))}
\NormalTok{\}}

\NormalTok{get\_loocv\_rmse }\OtherTok{=} \ControlFlowTok{function}\NormalTok{(model) \{}
  \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{mean}\NormalTok{((}\FunctionTok{resid}\NormalTok{(model) }\SpecialCharTok{/}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{{-}} \FunctionTok{hatvalues}\NormalTok{(model))) }\SpecialCharTok{\^{}} \DecValTok{2}\NormalTok{))}
\NormalTok{\}}

\NormalTok{get\_adj\_r2 }\OtherTok{=} \ControlFlowTok{function}\NormalTok{(model) \{}
  \FunctionTok{summary}\NormalTok{(model)}\SpecialCharTok{$}\NormalTok{adj.r.squared}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{get\_loocv\_rmse}\NormalTok{(mod\_b)}
\FunctionTok{get\_adj\_r2}\NormalTok{(mod\_b)}
\FunctionTok{get\_sw\_decision}\NormalTok{(mod\_b, }\AttributeTok{alpha =} \FloatTok{0.01}\NormalTok{)}
\FunctionTok{get\_num\_params}\NormalTok{(mod\_b)}
\end{Highlighting}
\end{Shaded}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{exercise-3-sacramento-housing-data}{%
\subsection{\texorpdfstring{Exercise 3 (\texttt{Sacramento} Housing
Data)}{Exercise 3 (Sacramento Housing Data)}}\label{exercise-3-sacramento-housing-data}}

For this exercise, use the \texttt{Sacramento} data from the
\texttt{caret} package. Use the following code to perform some
preprocessing of the data.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(caret)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: lattice
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'lattice'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:faraway':
## 
##     melanoma
\end{verbatim}

\begin{verbatim}
## Loading required package: ggplot2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{data}\NormalTok{(Sacramento)}
\NormalTok{sac\_data }\OtherTok{=}\NormalTok{ Sacramento}
\NormalTok{sac\_data}\SpecialCharTok{$}\NormalTok{limits }\OtherTok{=} \FunctionTok{factor}\NormalTok{(}\FunctionTok{ifelse}\NormalTok{(sac\_data}\SpecialCharTok{$}\NormalTok{city }\SpecialCharTok{==} \StringTok{"SACRAMENTO"}\NormalTok{, }\StringTok{"in"}\NormalTok{, }\StringTok{"out"}\NormalTok{))}
\NormalTok{sac\_data }\OtherTok{=} \FunctionTok{subset}\NormalTok{(sac\_data, }\AttributeTok{select =} \SpecialCharTok{{-}}\FunctionTok{c}\NormalTok{(city, zip))}
\end{Highlighting}
\end{Shaded}

Instead of using the \texttt{city} or \texttt{zip} variables that exist
in the dataset, we will simply create a variable (\texttt{limits})
indicating whether or not a house is technically within the city limits
of Sacramento. (We do this because they would both be factor variables
with a \textbf{large} number of levels. This is a choice that is made
due to laziness, not necessarily because it is justified. Think about
what issues these variables might cause.)

Use \texttt{?Sacramento} to learn more about this dataset.

A plot of longitude versus latitude gives us a sense of where the city
limits are.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{qplot}\NormalTok{(}\AttributeTok{y =}\NormalTok{ longitude, }\AttributeTok{x =}\NormalTok{ latitude, }\AttributeTok{data =}\NormalTok{ sac\_data,}
      \AttributeTok{col =}\NormalTok{ limits, }\AttributeTok{main =} \StringTok{"Sacramento City Limits "}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{w09-hw-fw9_files/figure-latex/unnamed-chunk-9-1.pdf}

After these modifications, we test-train split the data.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{420}\NormalTok{)}
\NormalTok{sac\_trn\_idx  }\OtherTok{=} \FunctionTok{sample}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(sac\_data), }\AttributeTok{size =} \FunctionTok{trunc}\NormalTok{(}\FloatTok{0.80} \SpecialCharTok{*} \FunctionTok{nrow}\NormalTok{(sac\_data)))}
\NormalTok{sac\_trn\_data }\OtherTok{=}\NormalTok{ sac\_data[sac\_trn\_idx, ]}
\NormalTok{sac\_tst\_data }\OtherTok{=}\NormalTok{ sac\_data[}\SpecialCharTok{{-}}\NormalTok{sac\_trn\_idx, ]}
\end{Highlighting}
\end{Shaded}

The training data should be used for all model fitting. Our goal is to
find a model that is useful for predicting home prices.

\textbf{(a)} Find a ``good'' model for \texttt{price}. Use any methods
seen in class. The model should reach a LOOCV-RMSE below 77,500 in the
training data. Do not use any transformations of the response variable.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sac\_mod\_3a }\OtherTok{=} \FunctionTok{lm}\NormalTok{(price }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{data =}\NormalTok{ sac\_trn\_data)}
\NormalTok{sac\_mod\_3a\_backward }\OtherTok{=} \FunctionTok{step}\NormalTok{(sac\_mod\_3a, }\AttributeTok{direction =} \StringTok{"backward"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Start:  AIC=16769
## price ~ beds + baths + sqft + type + latitude + longitude + limits
## 
##             Df Sum of Sq      RSS   AIC
## - baths      1  3.21e+09 4.34e+12 16767
## - limits     1  8.00e+09 4.34e+12 16768
## <none>                   4.33e+12 16769
## - type       2  4.46e+10 4.38e+12 16772
## - latitude   1  3.86e+10 4.37e+12 16773
## - longitude  1  1.20e+11 4.45e+12 16787
## - beds       1  1.38e+11 4.47e+12 16790
## - sqft       1  2.75e+12 7.09e+12 17133
## 
## Step:  AIC=16767
## price ~ beds + sqft + type + latitude + longitude + limits
## 
##             Df Sum of Sq      RSS   AIC
## - limits     1  7.00e+09 4.34e+12 16767
## <none>                   4.34e+12 16767
## - type       2  4.71e+10 4.39e+12 16771
## - latitude   1  3.73e+10 4.38e+12 16772
## - longitude  1  1.22e+11 4.46e+12 16786
## - beds       1  1.55e+11 4.49e+12 16792
## - sqft       1  3.88e+12 8.22e+12 17242
## 
## Step:  AIC=16767
## price ~ beds + sqft + type + latitude + longitude
## 
##             Df Sum of Sq      RSS   AIC
## <none>                   4.34e+12 16767
## - type       2  4.60e+10 4.39e+12 16770
## - latitude   1  3.67e+10 4.38e+12 16771
## - beds       1  1.54e+11 4.50e+12 16790
## - longitude  1  2.04e+11 4.55e+12 16799
## - sqft       1  4.00e+12 8.35e+12 17251
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{calc\_loocv\_rmse}\NormalTok{(sac\_mod\_3a\_backward)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 77393
\end{verbatim}

\textbf{(b)} Is a model that achieves a LOOCV-RMSE below 77,500 useful
in this case? That is, is an average error of 77,500 low enough when
predicting home prices? To further investigate, use the held-out test
data and your model from part \textbf{(a)} to do two things:

\begin{itemize}
\tightlist
\item
  Calculate the average percent error: \[
  \frac{1}{n}\sum_i\frac{|\text{predicted}_i - \text{actual}_i|}{\text{predicted}_i} \times 100
  \]
\item
  Plot the predicted versus the actual values and add the line
  \(y = x\).
\end{itemize}

Based on all of this information, argue whether or not this model is
useful.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{y\_hat }\OtherTok{=} \FunctionTok{predict}\NormalTok{(sac\_mod\_3a\_backward, }\AttributeTok{newdata =}\NormalTok{ sac\_tst\_data)}

\FunctionTok{sum}\NormalTok{((}\FunctionTok{abs}\NormalTok{(y\_hat }\SpecialCharTok{{-}}\NormalTok{ sac\_tst\_data}\SpecialCharTok{$}\NormalTok{price)) }\SpecialCharTok{/}\NormalTok{ y\_hat) }\SpecialCharTok{/} \FunctionTok{length}\NormalTok{(y\_hat) }\SpecialCharTok{*} \DecValTok{100}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 24.83
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(sac\_tst\_data}\SpecialCharTok{$}\NormalTok{price, y\_hat, }\AttributeTok{xlab =} \StringTok{"Actual Price"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"Predicted Price"}\NormalTok{, }\AttributeTok{col =} \StringTok{"grey"}\NormalTok{, }\AttributeTok{pch =} \DecValTok{20}\NormalTok{, }\AttributeTok{main =} \StringTok{"Predicted vs Actual"}\NormalTok{)}
\FunctionTok{abline}\NormalTok{(}\AttributeTok{a =} \DecValTok{0}\NormalTok{, }\AttributeTok{b =} \DecValTok{1}\NormalTok{, }\AttributeTok{col =} \StringTok{"orange"}\NormalTok{, }\AttributeTok{lwd =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{w09-hw-fw9_files/figure-latex/3.b-1.pdf}

The model is not useful since the error accounts for about 1/4 of the
price. Error is too large.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{exercise-4-does-it-work}{%
\subsection{Exercise 4 (Does It Work?)}\label{exercise-4-does-it-work}}

In this exercise, we will investigate how well backwards AIC and BIC
actually perform. For either to be ``working'' correctly, they should
result in a low number of both \textbf{false positives} and
\textbf{false negatives}. In model selection,

\begin{itemize}
\tightlist
\item
  \textbf{False Positive}, FP: Incorrectly including a variable in the
  model. Including a \emph{non-significant} variable
\item
  \textbf{False Negative}, FN: Incorrectly excluding a variable in the
  model. Excluding a \emph{significant} variable
\end{itemize}

Consider the \textbf{true} model

\[
Y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \beta_3 x_3 + \beta_4 x_4 + \beta_5 x_5 + \beta_6 x_6 + \beta_7 x_7 + \beta_8 x_8 + \beta_9 x_9 + \beta_{10} x_{10} + \epsilon
\]

where \(\epsilon \sim N(0, \sigma^2 = 4)\). The true values of the
\(\beta\) parameters are given in the \texttt{R} code below.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{beta\_0  }\OtherTok{=} \DecValTok{1}
\NormalTok{beta\_1  }\OtherTok{=} \SpecialCharTok{{-}}\DecValTok{1}
\NormalTok{beta\_2  }\OtherTok{=} \DecValTok{2}
\NormalTok{beta\_3  }\OtherTok{=} \SpecialCharTok{{-}}\DecValTok{2}
\NormalTok{beta\_4  }\OtherTok{=} \DecValTok{1}
\NormalTok{beta\_5  }\OtherTok{=} \DecValTok{1}
\NormalTok{beta\_6  }\OtherTok{=} \DecValTok{0}
\NormalTok{beta\_7  }\OtherTok{=} \DecValTok{0}
\NormalTok{beta\_8  }\OtherTok{=} \DecValTok{0}
\NormalTok{beta\_9  }\OtherTok{=} \DecValTok{0}
\NormalTok{beta\_10 }\OtherTok{=} \DecValTok{0}
\NormalTok{sigma }\OtherTok{=} \DecValTok{2}
\end{Highlighting}
\end{Shaded}

Then, as we have specified them, some variables are significant, and
some are not. We store their names in \texttt{R} variables for use
later.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{not\_sig  }\OtherTok{=} \FunctionTok{c}\NormalTok{(}\StringTok{"x\_6"}\NormalTok{, }\StringTok{"x\_7"}\NormalTok{, }\StringTok{"x\_8"}\NormalTok{, }\StringTok{"x\_9"}\NormalTok{, }\StringTok{"x\_10"}\NormalTok{)}
\NormalTok{signif }\OtherTok{=} \FunctionTok{c}\NormalTok{(}\StringTok{"x\_1"}\NormalTok{, }\StringTok{"x\_2"}\NormalTok{, }\StringTok{"x\_3"}\NormalTok{, }\StringTok{"x\_4"}\NormalTok{, }\StringTok{"x\_5"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

We now simulate values for these \texttt{x} variables, which we will use
throughout part \textbf{(a)}.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{420}\NormalTok{)}
\NormalTok{n }\OtherTok{=} \DecValTok{100}
\NormalTok{x\_1  }\OtherTok{=} \FunctionTok{runif}\NormalTok{(n, }\DecValTok{0}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\NormalTok{x\_2  }\OtherTok{=} \FunctionTok{runif}\NormalTok{(n, }\DecValTok{0}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\NormalTok{x\_3  }\OtherTok{=} \FunctionTok{runif}\NormalTok{(n, }\DecValTok{0}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\NormalTok{x\_4  }\OtherTok{=} \FunctionTok{runif}\NormalTok{(n, }\DecValTok{0}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\NormalTok{x\_5  }\OtherTok{=} \FunctionTok{runif}\NormalTok{(n, }\DecValTok{0}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\NormalTok{x\_6  }\OtherTok{=} \FunctionTok{runif}\NormalTok{(n, }\DecValTok{0}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\NormalTok{x\_7  }\OtherTok{=} \FunctionTok{runif}\NormalTok{(n, }\DecValTok{0}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\NormalTok{x\_8  }\OtherTok{=} \FunctionTok{runif}\NormalTok{(n, }\DecValTok{0}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\NormalTok{x\_9  }\OtherTok{=} \FunctionTok{runif}\NormalTok{(n, }\DecValTok{0}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\NormalTok{x\_10 }\OtherTok{=} \FunctionTok{runif}\NormalTok{(n, }\DecValTok{0}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

We then combine these into a data frame and simulate \texttt{y}
according to the true model.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sim\_data\_1 }\OtherTok{=} \FunctionTok{data.frame}\NormalTok{(x\_1, x\_2, x\_3, x\_4, x\_5, x\_6, x\_7, x\_8, x\_9, x\_10,}
  \AttributeTok{y =}\NormalTok{ beta\_0 }\SpecialCharTok{+}\NormalTok{ beta\_1 }\SpecialCharTok{*}\NormalTok{ x\_1 }\SpecialCharTok{+}\NormalTok{ beta\_2 }\SpecialCharTok{*}\NormalTok{ x\_2 }\SpecialCharTok{+}\NormalTok{ beta\_3 }\SpecialCharTok{*}\NormalTok{ x\_3 }\SpecialCharTok{+}\NormalTok{ beta\_4 }\SpecialCharTok{*}\NormalTok{ x\_4 }\SpecialCharTok{+} 
\NormalTok{      beta\_5 }\SpecialCharTok{*}\NormalTok{ x\_5 }\SpecialCharTok{+} \FunctionTok{rnorm}\NormalTok{(n, }\DecValTok{0}\NormalTok{ , sigma)}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

We do a quick check to make sure everything looks correct.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(sim\_data\_1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     x_1   x_2    x_3    x_4    x_5   x_6    x_7    x_8   x_9   x_10       y
## 1 6.055 4.088 8.7894 1.8180 0.8198 8.146 9.7305 9.6673 6.915 4.5523 -11.627
## 2 9.703 3.634 5.0768 5.5784 6.3193 6.033 3.2301 2.6707 2.214 0.4861  -0.147
## 3 1.745 3.899 0.5431 4.5068 1.0834 3.427 3.2223 5.2746 8.242 7.2310  15.145
## 4 4.758 5.315 7.6257 0.1287 9.4057 6.168 0.2472 6.5325 2.102 4.5814   2.404
## 5 7.245 7.225 9.5763 3.0398 0.4194 5.937 9.2169 4.6228 2.527 9.2349  -7.910
## 6 8.761 5.177 1.7983 0.5949 9.2944 9.392 1.0017 0.4476 5.508 5.9687   9.764
\end{verbatim}

Now, we fit an incorrect model.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit }\OtherTok{=} \FunctionTok{lm}\NormalTok{(y }\SpecialCharTok{\textasciitilde{}}\NormalTok{ x\_1 }\SpecialCharTok{+}\NormalTok{ x\_2 }\SpecialCharTok{+}\NormalTok{ x\_6 }\SpecialCharTok{+}\NormalTok{ x\_7, }\AttributeTok{data =}\NormalTok{ sim\_data\_1)}
\FunctionTok{coef}\NormalTok{(fit)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## (Intercept)         x_1         x_2         x_6         x_7 
##     -1.3758     -0.3572      2.1040      0.1344     -0.3367
\end{verbatim}

Notice, we have coefficients for \texttt{x\_1}, \texttt{x\_2},
\texttt{x\_6}, and \texttt{x\_7}. This means that \texttt{x\_6} and
\texttt{x\_7} are false positives, while \texttt{x\_3}, \texttt{x\_4},
and \texttt{x\_5} are false negatives.

To detect the false negatives, use:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# which are false negatives?}
\SpecialCharTok{!}\NormalTok{(signif }\SpecialCharTok{\%in\%} \FunctionTok{names}\NormalTok{(}\FunctionTok{coef}\NormalTok{(fit)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] FALSE FALSE  TRUE  TRUE  TRUE
\end{verbatim}

To detect the false positives, use:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# which are false positives?}
\FunctionTok{names}\NormalTok{(}\FunctionTok{coef}\NormalTok{(fit)) }\SpecialCharTok{\%in\%}\NormalTok{ not\_sig}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] FALSE FALSE FALSE  TRUE  TRUE
\end{verbatim}

Note that in both cases, you could \texttt{sum()} the result to obtain
the number of false negatives or positives.

\textbf{(a)} Set a seed equal to your birthday; then, using the given
data for each \texttt{x} variable above in \texttt{sim\_data\_1},
simulate the response variable \texttt{y} 300 times. Each time,

\begin{itemize}
\tightlist
\item
  Fit an additive model using each of the \texttt{x} variables.
\item
  Perform variable selection using backwards AIC.
\item
  Perform variable selection using backwards BIC.
\item
  Calculate and store the number of false negatives for the models
  chosen by AIC and BIC.
\item
  Calculate and store the number of false positives for the models
  chosen by AIC and BIC.
\end{itemize}

Calculate the rate of false positives and negatives for both AIC and
BIC. Compare the rates between the two methods. Arrange your results in
a well formatted table.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sim\_num }\OtherTok{=} \DecValTok{300}

\NormalTok{fn\_aic }\OtherTok{=} \FunctionTok{rep}\NormalTok{(}\DecValTok{0}\NormalTok{, sim\_num)}
\NormalTok{fp\_aic }\OtherTok{=} \FunctionTok{rep}\NormalTok{(}\DecValTok{0}\NormalTok{, sim\_num)}
\NormalTok{fn\_bic }\OtherTok{=} \FunctionTok{rep}\NormalTok{(}\DecValTok{0}\NormalTok{, sim\_num)}
\NormalTok{fp\_bic }\OtherTok{=} \FunctionTok{rep}\NormalTok{(}\DecValTok{0}\NormalTok{, sim\_num)}

\ControlFlowTok{for}\NormalTok{(i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\NormalTok{sim\_num) \{}
  
\NormalTok{  sim\_data\_1 }\OtherTok{=} \FunctionTok{data.frame}\NormalTok{(x\_1, x\_2, x\_3, x\_4, x\_5, x\_6, x\_7, x\_8, x\_9, x\_10,}
    \AttributeTok{y =}\NormalTok{ beta\_0 }\SpecialCharTok{+}\NormalTok{ beta\_1 }\SpecialCharTok{*}\NormalTok{ x\_1 }\SpecialCharTok{+}\NormalTok{ beta\_2 }\SpecialCharTok{*}\NormalTok{ x\_2 }\SpecialCharTok{+}\NormalTok{ beta\_3 }\SpecialCharTok{*}\NormalTok{ x\_3 }\SpecialCharTok{+}\NormalTok{ beta\_4 }\SpecialCharTok{*}\NormalTok{ x\_4 }\SpecialCharTok{+} 
\NormalTok{        beta\_5 }\SpecialCharTok{*}\NormalTok{ x\_5 }\SpecialCharTok{+} \FunctionTok{rnorm}\NormalTok{(n, }\DecValTok{0}\NormalTok{ , sigma))}
  
\NormalTok{  fit }\OtherTok{=} \FunctionTok{lm}\NormalTok{(y }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{data =}\NormalTok{ sim\_data\_1)}
\NormalTok{  fit\_bw\_aic }\OtherTok{=} \FunctionTok{step}\NormalTok{(fit, }\AttributeTok{direction =} \StringTok{"backward"}\NormalTok{, }\AttributeTok{trace=}\DecValTok{0}\NormalTok{)}
\NormalTok{  fit\_bw\_bic }\OtherTok{=} \FunctionTok{step}\NormalTok{(fit, }\AttributeTok{direction =} \StringTok{"backward"}\NormalTok{, }\AttributeTok{k =} \FunctionTok{log}\NormalTok{(n), }\AttributeTok{trace=}\DecValTok{0}\NormalTok{)}
  
\NormalTok{  fn\_aic[i] }\OtherTok{=} \FunctionTok{sum}\NormalTok{(}\SpecialCharTok{!}\NormalTok{(signif }\SpecialCharTok{\%in\%} \FunctionTok{names}\NormalTok{(}\FunctionTok{coef}\NormalTok{(fit\_bw\_aic))))}
\NormalTok{  fp\_aic[i] }\OtherTok{=} \FunctionTok{sum}\NormalTok{(}\FunctionTok{names}\NormalTok{(}\FunctionTok{coef}\NormalTok{(fit\_bw\_aic)) }\SpecialCharTok{\%in\%}\NormalTok{ not\_sig)}
  
  
\NormalTok{  fn\_bic[i] }\OtherTok{=} \FunctionTok{sum}\NormalTok{(}\SpecialCharTok{!}\NormalTok{(signif }\SpecialCharTok{\%in\%} \FunctionTok{names}\NormalTok{(}\FunctionTok{coef}\NormalTok{(fit\_bw\_bic))))}
\NormalTok{  fp\_bic[i] }\OtherTok{=} \FunctionTok{sum}\NormalTok{(}\FunctionTok{names}\NormalTok{(}\FunctionTok{coef}\NormalTok{(fit\_bw\_bic)) }\SpecialCharTok{\%in\%}\NormalTok{ not\_sig)}
\NormalTok{\}}

\NormalTok{df\_sim1 }\OtherTok{=} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{fp =} \FunctionTok{c}\NormalTok{(}\FunctionTok{mean}\NormalTok{(fp\_aic }\SpecialCharTok{/} \DecValTok{5}\NormalTok{), }\FunctionTok{mean}\NormalTok{(fp\_bic }\SpecialCharTok{/} \DecValTok{5}\NormalTok{)), }
                \AttributeTok{fn =} \FunctionTok{c}\NormalTok{(}\FunctionTok{mean}\NormalTok{(fn\_aic }\SpecialCharTok{/} \DecValTok{5}\NormalTok{), }\FunctionTok{mean}\NormalTok{(fn\_bic }\SpecialCharTok{/} \DecValTok{5}\NormalTok{)))}

\FunctionTok{row.names}\NormalTok{(df\_sim1) }\OtherTok{=} \FunctionTok{c}\NormalTok{(}\StringTok{"AIC"}\NormalTok{, }\StringTok{"BIC"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\textbf{(b)} Set a seed equal to your birthday; then, using the given
data for each \texttt{x} variable below in \texttt{sim\_data\_2},
simulate the response variable \texttt{y} 300 times. Each time,

\begin{itemize}
\tightlist
\item
  Fit an additive model using each of the \texttt{x} variables.
\item
  Perform variable selection using backwards AIC.
\item
  Perform variable selection using backwards BIC.
\item
  Calculate and store the number of false negatives for the models
  chosen by AIC and BIC.
\item
  Calculate and store the number of false positives for the models
  chosen by AIC and BIC.
\end{itemize}

Calculate the rate of false positives and negatives for both AIC and
BIC. Compare the rates between the two methods. Arrange your results in
a well formatted table. Also compare to your answers in part
\textbf{(a)} and suggest a reason for any differences.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{19880210}\NormalTok{)}
\NormalTok{x\_1  }\OtherTok{=} \FunctionTok{runif}\NormalTok{(n, }\DecValTok{0}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\NormalTok{x\_2  }\OtherTok{=} \FunctionTok{runif}\NormalTok{(n, }\DecValTok{0}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\NormalTok{x\_3  }\OtherTok{=} \FunctionTok{runif}\NormalTok{(n, }\DecValTok{0}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\NormalTok{x\_4  }\OtherTok{=} \FunctionTok{runif}\NormalTok{(n, }\DecValTok{0}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\NormalTok{x\_5  }\OtherTok{=} \FunctionTok{runif}\NormalTok{(n, }\DecValTok{0}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\NormalTok{x\_6  }\OtherTok{=} \FunctionTok{runif}\NormalTok{(n, }\DecValTok{0}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\NormalTok{x\_7  }\OtherTok{=} \FunctionTok{runif}\NormalTok{(n, }\DecValTok{0}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\NormalTok{x\_8  }\OtherTok{=}\NormalTok{ x\_1 }\SpecialCharTok{+} \FunctionTok{rnorm}\NormalTok{(n, }\DecValTok{0}\NormalTok{, }\FloatTok{0.1}\NormalTok{)}
\NormalTok{x\_9  }\OtherTok{=}\NormalTok{ x\_1 }\SpecialCharTok{+} \FunctionTok{rnorm}\NormalTok{(n, }\DecValTok{0}\NormalTok{, }\FloatTok{0.1}\NormalTok{)}
\NormalTok{x\_10 }\OtherTok{=}\NormalTok{ x\_2 }\SpecialCharTok{+} \FunctionTok{rnorm}\NormalTok{(n, }\DecValTok{0}\NormalTok{, }\FloatTok{0.1}\NormalTok{)}

\NormalTok{sim\_data\_2 }\OtherTok{=} \FunctionTok{data.frame}\NormalTok{(x\_1, x\_2, x\_3, x\_4, x\_5, x\_6, x\_7, x\_8, x\_9, x\_10,}
  \AttributeTok{y =}\NormalTok{ beta\_0 }\SpecialCharTok{+}\NormalTok{ beta\_1 }\SpecialCharTok{*}\NormalTok{ x\_1 }\SpecialCharTok{+}\NormalTok{ beta\_2 }\SpecialCharTok{*}\NormalTok{ x\_2 }\SpecialCharTok{+}\NormalTok{ beta\_3 }\SpecialCharTok{*}\NormalTok{ x\_3 }\SpecialCharTok{+}\NormalTok{ beta\_4 }\SpecialCharTok{*}\NormalTok{ x\_4 }\SpecialCharTok{+} 
\NormalTok{      beta\_5 }\SpecialCharTok{*}\NormalTok{ x\_5 }\SpecialCharTok{+} \FunctionTok{rnorm}\NormalTok{(n, }\DecValTok{0}\NormalTok{ , sigma)}
\NormalTok{)}


\NormalTok{sim\_num }\OtherTok{=} \DecValTok{300}

\NormalTok{fn\_aic }\OtherTok{=} \FunctionTok{rep}\NormalTok{(}\DecValTok{0}\NormalTok{, sim\_num)}
\NormalTok{fp\_aic }\OtherTok{=} \FunctionTok{rep}\NormalTok{(}\DecValTok{0}\NormalTok{, sim\_num)}
\NormalTok{fn\_bic }\OtherTok{=} \FunctionTok{rep}\NormalTok{(}\DecValTok{0}\NormalTok{, sim\_num)}
\NormalTok{fp\_bic }\OtherTok{=} \FunctionTok{rep}\NormalTok{(}\DecValTok{0}\NormalTok{, sim\_num)}

\ControlFlowTok{for}\NormalTok{(i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\NormalTok{sim\_num) \{}
  
\NormalTok{  sim\_data\_2 }\OtherTok{=} \FunctionTok{data.frame}\NormalTok{(x\_1, x\_2, x\_3, x\_4, x\_5, x\_6, x\_7, x\_8, x\_9, x\_10,}
    \AttributeTok{y =}\NormalTok{ beta\_0 }\SpecialCharTok{+}\NormalTok{ beta\_1 }\SpecialCharTok{*}\NormalTok{ x\_1 }\SpecialCharTok{+}\NormalTok{ beta\_2 }\SpecialCharTok{*}\NormalTok{ x\_2 }\SpecialCharTok{+}\NormalTok{ beta\_3 }\SpecialCharTok{*}\NormalTok{ x\_3 }\SpecialCharTok{+}\NormalTok{ beta\_4 }\SpecialCharTok{*}\NormalTok{ x\_4 }\SpecialCharTok{+} 
\NormalTok{        beta\_5 }\SpecialCharTok{*}\NormalTok{ x\_5 }\SpecialCharTok{+} \FunctionTok{rnorm}\NormalTok{(n, }\DecValTok{0}\NormalTok{ , sigma)}
\NormalTok{  )}
  
\NormalTok{  fit }\OtherTok{=} \FunctionTok{lm}\NormalTok{(y }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{data =}\NormalTok{ sim\_data\_2)}
\NormalTok{  fit\_bw\_aic }\OtherTok{=} \FunctionTok{step}\NormalTok{(fit, }\AttributeTok{direction =} \StringTok{"backward"}\NormalTok{, }\AttributeTok{trace=}\DecValTok{0}\NormalTok{)}
\NormalTok{  fit\_bw\_bic }\OtherTok{=} \FunctionTok{step}\NormalTok{(fit, }\AttributeTok{direction =} \StringTok{"backward"}\NormalTok{, }\AttributeTok{k =} \FunctionTok{log}\NormalTok{(n), }\AttributeTok{trace=}\DecValTok{0}\NormalTok{)}
  
\NormalTok{  fn\_aic[i] }\OtherTok{=} \FunctionTok{sum}\NormalTok{(}\SpecialCharTok{!}\NormalTok{(signif }\SpecialCharTok{\%in\%} \FunctionTok{names}\NormalTok{(}\FunctionTok{coef}\NormalTok{(fit\_bw\_aic))))}
\NormalTok{  fp\_aic[i] }\OtherTok{=} \FunctionTok{sum}\NormalTok{(}\FunctionTok{names}\NormalTok{(}\FunctionTok{coef}\NormalTok{(fit\_bw\_aic)) }\SpecialCharTok{\%in\%}\NormalTok{ not\_sig)}
  
  
\NormalTok{  fn\_bic[i] }\OtherTok{=} \FunctionTok{sum}\NormalTok{(}\SpecialCharTok{!}\NormalTok{(signif }\SpecialCharTok{\%in\%} \FunctionTok{names}\NormalTok{(}\FunctionTok{coef}\NormalTok{(fit\_bw\_bic))))}
\NormalTok{  fp\_bic[i] }\OtherTok{=} \FunctionTok{sum}\NormalTok{(}\FunctionTok{names}\NormalTok{(}\FunctionTok{coef}\NormalTok{(fit\_bw\_bic)) }\SpecialCharTok{\%in\%}\NormalTok{ not\_sig)}
\NormalTok{\}}

\NormalTok{df\_sim2 }\OtherTok{=} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{fp =} \FunctionTok{c}\NormalTok{(}\FunctionTok{mean}\NormalTok{(fp\_aic }\SpecialCharTok{/} \DecValTok{5}\NormalTok{), }\FunctionTok{mean}\NormalTok{(fp\_bic }\SpecialCharTok{/} \DecValTok{5}\NormalTok{)), }
                \AttributeTok{fn =} \FunctionTok{c}\NormalTok{(}\FunctionTok{mean}\NormalTok{(fn\_aic }\SpecialCharTok{/} \DecValTok{5}\NormalTok{), }\FunctionTok{mean}\NormalTok{(fn\_bic }\SpecialCharTok{/} \DecValTok{5}\NormalTok{)))}

\FunctionTok{row.names}\NormalTok{(df\_sim2) }\OtherTok{=} \FunctionTok{c}\NormalTok{(}\StringTok{"AIC"}\NormalTok{, }\StringTok{"BIC"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Simulation 1 has lower false positive rate for both AIC and BIC compared
to simulation 2.\\
Simulation 1's false negative rate are 0 and simulation 2's false
negative rate is around 0.16-0.17.

This is because the collinearity of x1, x8, x9 and x2, x10. The search
might find x8, x9 and x10 as significant, resulting in increased false
positive. When x8, x9 and x10 is selected, x1 and x2 are considered
non-significant, resuliting in increased false negative.

\end{document}
